version: "3.9"
services:
  nextjs:
    image: oronila/nextjs:latest
    container_name: nextjs
    build: ./
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: oronila/nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/origin.crt:/etc/nginx/certs/origin.crt:ro
      - ./nginx/origin.key:/etc/nginx/certs/origin.key:ro
    restart: always