import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import { Amplify } from "aws-amplify";
import { Authenticator as AmplifyAuthenticator } from "@aws-amplify/ui-react";
import ClientComponent from "./clientLayout";
const mont = Montserrat({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });


 

export const metadata: Metadata = {
 title: "Fynopsis",
 description: "Generated by create next app",
};


export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
   <html lang="en">
     <body className={inter.className}>
      <ClientComponent>
        {children}
      </ClientComponent>
      </body>
   </html>
 );
}
