import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import { Amplify } from "aws-amplify";
const mont = Montserrat({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });




Amplify.configure({
 Auth: {
   Cognito: {
     //  Amazon Cognito User Pool ID
     userPoolId: 'us-east-1_ngn1sHNPR',
     // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
     userPoolClientId: '70qevjjp7hvp31c839e4gldj29',
     // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
     // identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
     // OPTIONAL - Set to true to use your identity pool's unauthenticated role when user is not logged in
     // allowGuestAccess: true,
     // // OPTIONAL - This is used when autoSignIn is enabled for Auth.signUp
     // // 'code' is used for Auth.confirmSignUp, 'link' is used for email link verification
     signUpVerificationMethod: 'link', // 'code' | 'link'
   }
 }
});




export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};


export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
   <html lang="en">
     <body className={mont.className}>{children}</body>
   </html>
 );
}
